# Generated by Django 3.2.5 on 2022-06-16 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20220530_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(help_text='User that have made this order', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='form',
            field=models.CharField(choices=[('TAB', 'Tabletki'), ('SYR', 'Syrop'), ('G', 'Żel'), ('ML', 'Płyn'), ('H', 'Saszetki')], help_text='The form of the product, eg. tablets, syrup etc.', max_length=3),
        ),
    ]
