# Generated by Django 3.2.5 on 2022-06-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220616_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='pre_payment', help_text='The current status of the order', max_length=11, verbose_name=(('pre_payment', 'Awaiting payment'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled'))),
        ),
    ]
