# Generated by Django 3.2.5 on 2022-06-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='composition',
            field=models.TextField(default='brak składu', help_text='The composition of the product'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='brak opisu', help_text='The description of the product'),
        ),
    ]
