# Generated by Django 3.2.5 on 2022-06-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pre_payment', 'Oczekiwanie na zapłatę'), ('processing', 'W realizacji'), ('shipped', 'Wysłano'), ('completed', 'Zrealizowano'), ('cancelled', 'Anulowano')], default='pre_payment', help_text='The current status of the order', max_length=11),
        ),
    ]
