# Generated by Django 3.2.5 on 2022-06-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220621_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='local_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
