# Generated by Django 3.2.5 on 2022-06-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220621_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('dhl', 'Kurier DHL'), ('inpost', 'Paczkomaty inPost'), ('poczta_polska', 'Poczta Polska')], default='dhl', help_text='Delivery method chosen by the customer', max_length=13),
        ),
    ]
